input_topics:
  ["/d405/camera/depth/color/points", "/d455/camera/depth/color/points"]
concat_frame: "panda_link0"
filtered_output: "/points"
max_correspondence_distance: 0.5
transformation_epsilon: 0.00000000001
fitness_epsilon: 0.001
max_iterations: 500

## Filters

# Box Filter

# only cylinder
box_min: [0.42, -0.127, 0]
box_max: [0.46, -0.075, 0.05]

# entire box
# box_min: [0.2, -0.4064, 0]
# box_max: [0.9398, 0.4064, 0.20]

#Outlier filter
outlier_mean: 50
outlier_stddev: 2
